// templates/application/preact/js/src/App.jsx
import { render, h } from "preact";

import "./index.{{CSS_EXTENSION}}";

const App = () => (
  <div class="{{CONTAINER}}">
    <div>Name: {{ NAME }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
);
render(<App />, document.getElementById("app"));

// templates/lit-html/ts/src/App.ts
import { html, render } from "lit-html";

import "./index.{{CSS_EXTENSION}}";

const myTemplate = html`<div class="{{CONTAINER}}">
  <div>Name: {{ NAME }}</div>
  <div>Framework: {{ FRAMEWORK }}</div>
  <div>Language: {{ LANGUAGE }}</div>
  <div>CSS: {{ CSS }}</div>
</div>`;

render(myTemplate, document.getElementById("app"));
