// templates/preact/js/src/App.jsx
import { render, h } from "preact";

import "./index.{{CSS_EXTENSION}}";

const App = () => (
  <div class="{{CONTAINER}}">
    <div>Host: {{ NAME }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
);
render(<App />, document.getElementById("app"));

// templates/solid-js/js/src/App.jsx
import { render } from "solid-js/web";

import "./index.{{CSS_EXTENSION}}";

const App = () => (
  <div class="{{CONTAINER}}">
    <div>Host: {{ NAME }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
);
render(App, document.getElementById("app"));
